/**
 * This class is generated by jOOQ
 */
package cn.linpeng.model.tables;


import cn.linpeng.model.Keys;
import cn.linpeng.model.Xcms;
import cn.linpeng.model.tables.records.AppRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends TableImpl<AppRecord> {

	private static final long serialVersionUID = -493566891;

	/**
	 * The reference instance of <code>xcms.app</code>
	 */
	public static final App APP = new App();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppRecord> getRecordType() {
		return AppRecord.class;
	}

	/**
	 * The column <code>xcms.app.id</code>.
	 */
	public final TableField<AppRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.app.user_id</code>.
	 */
	public final TableField<AppRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.app.type</code>.
	 */
	public final TableField<AppRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.app.create_time</code>.
	 */
	public final TableField<AppRecord, Date> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>xcms.app.theme</code>.
	 */
	public final TableField<AppRecord, Integer> THEME = createField("theme", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.app.domain</code>. 应用上下文
	 */
	public final TableField<AppRecord, String> DOMAIN = createField("domain", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "应用上下文");

	/**
	 * Create a <code>xcms.app</code> table reference
	 */
	public App() {
		this("app", null);
	}

	/**
	 * Create an aliased <code>xcms.app</code> table reference
	 */
	public App(String alias) {
		this(alias, APP);
	}

	private App(String alias, Table<AppRecord> aliased) {
		this(alias, aliased, null);
	}

	private App(String alias, Table<AppRecord> aliased, Field<?>[] parameters) {
		super(alias, Xcms.XCMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AppRecord, Integer> getIdentity() {
		return Keys.IDENTITY_APP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AppRecord> getPrimaryKey() {
		return Keys.KEY_APP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AppRecord>> getKeys() {
		return Arrays.<UniqueKey<AppRecord>>asList(Keys.KEY_APP_PRIMARY, Keys.KEY_APP_UNI_APP_DOMAIN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public App as(String alias) {
		return new App(alias, this);
	}

	/**
	 * Rename this table
	 */
	public App rename(String name) {
		return new App(name, null);
	}
}
