/**
 * This class is generated by jOOQ
 */
package cn.linpeng.model.tables;


import cn.linpeng.model.Keys;
import cn.linpeng.model.Xcms;
import cn.linpeng.model.tables.records.CategoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Category extends TableImpl<CategoryRecord> {

	private static final long serialVersionUID = -1696240784;

	/**
	 * The reference instance of <code>xcms.category</code>
	 */
	public static final Category CATEGORY = new Category();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CategoryRecord> getRecordType() {
		return CategoryRecord.class;
	}

	/**
	 * The column <code>xcms.category.id</code>.
	 */
	public final TableField<CategoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.category.name</code>.
	 */
	public final TableField<CategoryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>xcms.category.remark</code>.
	 */
	public final TableField<CategoryRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>xcms.category.app_id</code>.
	 */
	public final TableField<CategoryRecord, Integer> APP_ID = createField("app_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.category.uri</code>.
	 */
	public final TableField<CategoryRecord, String> URI = createField("uri", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * Create a <code>xcms.category</code> table reference
	 */
	public Category() {
		this("category", null);
	}

	/**
	 * Create an aliased <code>xcms.category</code> table reference
	 */
	public Category(String alias) {
		this(alias, CATEGORY);
	}

	private Category(String alias, Table<CategoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Category(String alias, Table<CategoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Xcms.XCMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CategoryRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CategoryRecord> getPrimaryKey() {
		return Keys.KEY_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CategoryRecord>> getKeys() {
		return Arrays.<UniqueKey<CategoryRecord>>asList(Keys.KEY_CATEGORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Category as(String alias) {
		return new Category(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Category rename(String name) {
		return new Category(name, null);
	}
}
