/**
 * This class is generated by jOOQ
 */
package cn.linpeng.model.tables;


import cn.linpeng.model.Keys;
import cn.linpeng.model.Xcms;
import cn.linpeng.model.tables.records.PostRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post extends TableImpl<PostRecord> {

	private static final long serialVersionUID = -188245448;

	/**
	 * The reference instance of <code>xcms.post</code>
	 */
	public static final Post POST = new Post();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PostRecord> getRecordType() {
		return PostRecord.class;
	}

	/**
	 * The column <code>xcms.post.id</code>.
	 */
	public final TableField<PostRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.post.app_id</code>.
	 */
	public final TableField<PostRecord, Integer> APP_ID = createField("app_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.post.title</code>.
	 */
	public final TableField<PostRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * The column <code>xcms.post.summary</code>.
	 */
	public final TableField<PostRecord, String> SUMMARY = createField("summary", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * The column <code>xcms.post.content</code>.
	 */
	public final TableField<PostRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>xcms.post.author</code>.
	 */
	public final TableField<PostRecord, Integer> AUTHOR = createField("author", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>xcms.post.create_time</code>.
	 */
	public final TableField<PostRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>xcms.post.category_id</code>.
	 */
	public final TableField<PostRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>xcms.post</code> table reference
	 */
	public Post() {
		this("post", null);
	}

	/**
	 * Create an aliased <code>xcms.post</code> table reference
	 */
	public Post(String alias) {
		this(alias, POST);
	}

	private Post(String alias, Table<PostRecord> aliased) {
		this(alias, aliased, null);
	}

	private Post(String alias, Table<PostRecord> aliased, Field<?>[] parameters) {
		super(alias, Xcms.XCMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PostRecord, Integer> getIdentity() {
		return Keys.IDENTITY_POST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PostRecord> getPrimaryKey() {
		return Keys.KEY_POST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PostRecord>> getKeys() {
		return Arrays.<UniqueKey<PostRecord>>asList(Keys.KEY_POST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Post as(String alias) {
		return new Post(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Post rename(String name) {
		return new Post(name, null);
	}
}
