/**
 * This class is generated by jOOQ
 */
package cn.linpeng.model.tables.records;


import cn.linpeng.model.tables.App;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppRecord extends UpdatableRecordImpl<AppRecord> implements Record6<Integer, Integer, Integer, Date, Integer, String> {

	private static final long serialVersionUID = 330251704;

	/**
	 * Setter for <code>xcms.app.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>xcms.app.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>xcms.app.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>xcms.app.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>xcms.app.type</code>.
	 */
	public void setType(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>xcms.app.type</code>.
	 */
	public Integer getType() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>xcms.app.create_time</code>.
	 */
	public void setCreateTime(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>xcms.app.create_time</code>.
	 */
	public Date getCreateTime() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>xcms.app.theme</code>.
	 */
	public void setTheme(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>xcms.app.theme</code>.
	 */
	public Integer getTheme() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>xcms.app.domain</code>. 应用上下文
	 */
	public void setDomain(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>xcms.app.domain</code>. 应用上下文
	 */
	public String getDomain() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Date, Integer, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Date, Integer, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return App.APP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return App.APP.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return App.APP.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return App.APP.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return App.APP.THEME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return App.APP.DOMAIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getTheme();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getDomain();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppRecord value2(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppRecord value3(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppRecord value4(Date value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppRecord value5(Integer value) {
		setTheme(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppRecord value6(String value) {
		setDomain(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppRecord values(Integer value1, Integer value2, Integer value3, Date value4, Integer value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppRecord
	 */
	public AppRecord() {
		super(App.APP);
	}

	/**
	 * Create a detached, initialised AppRecord
	 */
	public AppRecord(Integer id, Integer userId, Integer type, Date createTime, Integer theme, String domain) {
		super(App.APP);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, type);
		setValue(3, createTime);
		setValue(4, theme);
		setValue(5, domain);
	}
}
