/**
 * This class is generated by jOOQ
 */
package cn.linpeng.model.tables.records;


import cn.linpeng.model.tables.Post;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostRecord extends UpdatableRecordImpl<PostRecord> implements Record8<Integer, Integer, String, String, String, Integer, Timestamp, Integer> {

	private static final long serialVersionUID = 1276204722;

	/**
	 * Setter for <code>xcms.post.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>xcms.post.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>xcms.post.app_id</code>.
	 */
	public void setAppId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>xcms.post.app_id</code>.
	 */
	public Integer getAppId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>xcms.post.title</code>.
	 */
	public void setTitle(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>xcms.post.title</code>.
	 */
	public String getTitle() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>xcms.post.summary</code>.
	 */
	public void setSummary(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>xcms.post.summary</code>.
	 */
	public String getSummary() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>xcms.post.content</code>.
	 */
	public void setContent(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>xcms.post.content</code>.
	 */
	public String getContent() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>xcms.post.author</code>.
	 */
	public void setAuthor(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>xcms.post.author</code>.
	 */
	public Integer getAuthor() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>xcms.post.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>xcms.post.create_time</code>.
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>xcms.post.category_id</code>.
	 */
	public void setCategoryId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>xcms.post.category_id</code>.
	 */
	public Integer getCategoryId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, String, Integer, Timestamp, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, String, Integer, Timestamp, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Post.POST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Post.POST.APP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Post.POST.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Post.POST.SUMMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Post.POST.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Post.POST.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Post.POST.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Post.POST.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getAppId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getSummary();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value2(Integer value) {
		setAppId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value3(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value4(String value) {
		setSummary(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value5(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value6(Integer value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value7(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value8(Integer value) {
		setCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Integer value6, Timestamp value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PostRecord
	 */
	public PostRecord() {
		super(Post.POST);
	}

	/**
	 * Create a detached, initialised PostRecord
	 */
	public PostRecord(Integer id, Integer appId, String title, String summary, String content, Integer author, Timestamp createTime, Integer categoryId) {
		super(Post.POST);

		setValue(0, id);
		setValue(1, appId);
		setValue(2, title);
		setValue(3, summary);
		setValue(4, content);
		setValue(5, author);
		setValue(6, createTime);
		setValue(7, categoryId);
	}
}
