/**
 * This class is generated by jOOQ
 */
package cn.linpeng.model;


import cn.linpeng.model.tables.App;
import cn.linpeng.model.tables.Category;
import cn.linpeng.model.tables.Comment;
import cn.linpeng.model.tables.Post;
import cn.linpeng.model.tables.Tag;
import cn.linpeng.model.tables.Theme;
import cn.linpeng.model.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in xcms
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table xcms.app
	 */
	public static final App APP = cn.linpeng.model.tables.App.APP;

	/**
	 * The table xcms.category
	 */
	public static final Category CATEGORY = cn.linpeng.model.tables.Category.CATEGORY;

	/**
	 * The table xcms.comment
	 */
	public static final Comment COMMENT = cn.linpeng.model.tables.Comment.COMMENT;

	/**
	 * The table xcms.post
	 */
	public static final Post POST = cn.linpeng.model.tables.Post.POST;

	/**
	 * The table xcms.tag
	 */
	public static final Tag TAG = cn.linpeng.model.tables.Tag.TAG;

	/**
	 * The table xcms.theme
	 */
	public static final Theme THEME = cn.linpeng.model.tables.Theme.THEME;

	/**
	 * The table xcms.user
	 */
	public static final User USER = cn.linpeng.model.tables.User.USER;
}
